import random
x =int(input("     ENTER FIRST VALUE:\n"))
y = int(input("     ENTER SECOND VALUE:\n"))
print(("\n") +"=",x + y)
print("\n")
print("\n")
print("\n")    
chara = input('   Enter a character\n\n')
gg = str(random.choice(chara))
print(str(gg))
print("\n")
print("\n")
exp = eval(input('   Enter an expression\n\n'))
print("\n")
print(exp)